# Site settings
title: Awesome ADHD
email: bradleydunc@gmail.com
description: >- 
  A curated list of ADHD apps, books, ideas and resources across the web! 
baseurl: "/awesome-adhd" 
url: "http://xargsuk.github.io"
twitter_username: _bradduncan
github_username: XargsUK

# Build settings
# markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false

assets:
  - assets/main.css

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
